services:
    college_crazies.component.authentication.handler.login_success_handler:
        class:  CollegeCrazies\Bundle\SecurityBundle\Component\Authentication\Handler\LoginSuccessHandler
        arguments:
            - @router
            - @security.context
            - @session
            - @doctrine.orm.entity_manager
        tags:
            - { name: 'monolog.logger', channel: 'security' }
