services:
    sofachamps.mm.repo.bracket:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - SofaChampsMarchMadnessBundle:Bracket
