services:
    twig.extension.sofachamps.superbowlchallenge:
        class: SofaChamps\Bundle\SuperBowlChallengeBundle\Twig\Extension\SuperBowlChallengeExtension
        public: false
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
