imports:
    - { resource: "@SofaChampsCoreBundle/Resources/config/services.yml" }
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: { fallback: en }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Sonata Admin
sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node, /usr/local/lib/node_modules]
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_all_services: false

jms_di_extra:
    locations:
        all_bundles: true
        directories: ["%kernel.root_dir%/../src"]

jms_serializer:
    metadata:
        directories:
            fosuserbundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "%kernel.root_dir%/serializer/FOSUserBundle"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SofaChamps\Bundle\CoreBundle\Entity\User
    service:
       user_manager: sofachamps.user.manager
    registration:
        form:
            type: "sofachamps_user_registration"
    profile:
        form:
            type: "sofachamps_user_profile"

vlabs_media:
    image_cache:
        cache_dir: "uploads/bp/cache"
    mapping:
        image_entity:
            class: SofaChamps\Bundle\CoreBundle\Entity\Image
    templates:
        image: SofaChampsCoreBundle:Vlabs:image.html.twig

fos_facebook:
    alias:  facebook
    app_id: %facebook.app_id%
    secret: %facebook.secret%
    cookie: true
    permissions: [email]

liip_doctrine_cache:
    namespaces:
        gearman:
            type: file_system

gearman:
    bundles:
        email:
            name: SofaChampsEmailBundle
            active: true
            ignore:
                - Tests
        bowl-picket:
            name: SofaChampsBowlPickemBundle
            active: true
            include:
                - Event
            ignore:
                - Tests
        core:
            name: SofaChampsCoreBundle
            ignore:
                - Tests
    servers:
        localhost:
            host: 127.0.0.1
            port: 4730
