services:
    listener.picks_locked:
        class: CollegeCrazies\Bundle\MainBundle\Listener\PicksLockedListener
        arguments:
            - @doctrine.orm.entity_manager
            - @session
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
