services:
    event.subscriber.game:
        class: SofaChamps\Bundle\BowlPickemBundle\Event\GameSubscriber
        arguments:
            - @pickset.analyzer
            - @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_subscriber }
