services:
    twig.extension.sofachamps.app:
        class: SofaChamps\Bundle\BowlPickemBundle\Twig\Extension\AppExtension
        public: false
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }

    twig.extension.sofachamps.text:
        class: SofaChamps\Bundle\BowlPickemBundle\Twig\Extension\TextExtension
        public: false
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
